### ISSUE TITLE
Erro no diretório das imagens

### ISSUE THREAD

**Issue by lrlucena** [henriqueap/Nest2#1]
As imagens estão em um diretorio diferente do especificado no programa. Precisa alterar o código.

**Comment by henriqueap** [comment]
Obrigado professor, vou dar uma ajustada, mas, o senhor chegou a ver o
jogo? O senhor vai estar hoje no IFRN?

Em 8 de mar de 2017 11:09 AM, "Leonardo Lucena" <notifications@github.com>
escreveu:
